version: '3.3'
services:
    php:
        image: php:7.4-cli
        command: php -S 0.0.0.0:8080
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - 8085:8080
